"""ISO 27001 Annex A control-to-evidence mapping."""
from __future__ import annotations

from compliance.controls.soc2 import ControlSpec


ISO27001_CONTROLS: list[ControlSpec] = [
    ControlSpec(
        control_id="A.5.1",
        name="Policies for information security",
        description="A set of policies for information security shall be defined, approved, published, and communicated",
        source="docs",
        method="export_policies",
        freshness_days=365,
    ),
    ControlSpec(
        control_id="A.6.1",
        name="Organization of information security - Roles and responsibilities",
        description="Information security responsibilities shall be defined and allocated",
        source="okta",
        method="export_roles",
        freshness_days=90,
    ),
    ControlSpec(
        control_id="A.8.1",
        name="Asset Management - Inventory of assets",
        description="Assets associated with information shall be identified and an inventory maintained",
        source="wazuh",
        method="export_agent_inventory",
        freshness_days=14,
    ),
    ControlSpec(
        control_id="A.9.1",
        name="Access Control Policy",
        description="An access control policy shall be established, documented, and reviewed",
        source="okta",
        method="export_access_policies",
        freshness_days=30,
    ),
    ControlSpec(
        control_id="A.9.2",
        name="User Access Management - JML",
        description="Joiner/Mover/Leaver process is documented and enforced",
        source="okta",
        method="export_jml_audit",
        freshness_days=30,
    ),
    ControlSpec(
        control_id="A.9.4",
        name="System Access Control - Authentication",
        description="Access to systems and applications shall be controlled by a secure log-on procedure",
        source="okta",
        method="export_mfa_policies",
        freshness_days=30,
    ),
    ControlSpec(
        control_id="A.10.1",
        name="Cryptographic Controls",
        description="Cryptographic controls shall be developed and implemented",
        source="intune",
        method="export_encryption_compliance",
        freshness_days=14,
    ),
    ControlSpec(
        control_id="A.12.1",
        name="Operational procedures and responsibilities",
        description="Operating procedures shall be documented and made available",
        source="docs",
        method="export_runbooks",
        freshness_days=180,
    ),
    ControlSpec(
        control_id="A.12.4",
        name="Logging and Monitoring",
        description="Event logs recording user activities, exceptions, faults, and information security events shall be produced, kept, and regularly reviewed",
        source="wazuh",
        method="export_log_retention_status",
        freshness_days=30,
    ),
    ControlSpec(
        control_id="A.12.6",
        name="Vulnerability Management",
        description="Information about technical vulnerabilities of systems shall be obtained in a timely fashion",
        source="wazuh",
        method="export_vulnerability_summary",
        freshness_days=7,
    ),
    ControlSpec(
        control_id="A.13.1",
        name="Network Security Management",
        description="Networks shall be managed and controlled to protect information in systems and applications",
        source="docs",
        method="export_network_diagrams",
        freshness_days=180,
    ),
    ControlSpec(
        control_id="A.14.2",
        name="Security in development and support processes",
        description="Rules for the development of software and systems shall be established",
        source="git",
        method="export_recent_commits",
        freshness_days=30,
    ),
    ControlSpec(
        control_id="A.16.1",
        name="Information Security Incident Management",
        description="Management responsibilities and procedures shall be established to ensure a quick, effective, and orderly response",
        source="thehive",
        method="export_case_metrics",
        freshness_days=14,
    ),
    ControlSpec(
        control_id="A.18.1",
        name="Compliance with legal and contractual requirements",
        description="All relevant legislative statutory, regulatory, contractual requirements shall be explicitly identified",
        source="docs",
        method="export_compliance_register",
        freshness_days=180,
    ),
]
