---
# ══════════════════════════════════════════════════════════════════════════════
# corpsec-ops-platform — Ansible inventory
# ══════════════════════════════════════════════════════════════════════════════

all:
  vars:
    wazuh_manager_address: wazuh-manager.corpsec.local
    wazuh_manager_port: 1514
    wazuh_registration_port: 1515

  children:
    linux_endpoints:
      hosts:
        endpoint-linux-01:
          ansible_host: 10.10.10.21
          ansible_user: ansible
          ansible_python_interpreter: /usr/bin/python3
      vars:
        os_family: linux
        cis_profile: server-l1

    windows_endpoints:
      hosts:
        endpoint-win-01:
          ansible_host: 10.10.10.31
          ansible_user: ansible
          ansible_password: "{{ lookup('env', 'WIN_ANSIBLE_PASSWORD') }}"
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5985
      vars:
        os_family: windows
        cis_profile: workstation-l1

    soc_team:
      hosts:
        soc-laptop-alice:
          ansible_host: 10.10.10.41
          ansible_user: alice
          os_family: macos
        soc-laptop-bob:
          ansible_host: 10.10.10.42
          ansible_user: bob
          os_family: macos
