apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: false

  - name: Wazuh-Indexer
    type: elasticsearch
    uid: wazuh-indexer
    access: proxy
    url: https://wazuh-indexer:9200
    database: "wazuh-alerts-*"
    basicAuth: true
    basicAuthUser: ${WAZUH_INDEXER_USERNAME}
    secureJsonData:
      basicAuthPassword: ${WAZUH_INDEXER_PASSWORD}
    jsonData:
      tlsSkipVerify: true
      timeField: "@timestamp"
      esVersion: "7.10.2"
    editable: false

  - name: TheHive-ES
    type: elasticsearch
    uid: thehive-es
    access: proxy
    url: http://thehive-index:9200
    database: "thehive_*"
    jsonData:
      timeField: "createdAt"
      esVersion: "7.17.0"
    editable: false
